/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.css",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#001e40',
        'on-primary': '#ffffff',
        'primary-container': '#003366',
        'on-primary-container': '#799dd6',
        'primary-fixed': '#d5e3ff',
        'primary-fixed-dim': '#a7c8ff',
        'on-primary-fixed': '#001b3c',
        'on-primary-fixed-variant': '#1f477b',
        secondary: '#a04100',
        'on-secondary': '#ffffff',
        'secondary-container': '#fe6b00',
        'on-secondary-container': '#572000',
        'secondary-fixed': '#ffdbcc',
        'secondary-fixed-dim': '#ffb693',
        'on-secondary-fixed': '#351000',
        'on-secondary-fixed-variant': '#7a3000',
        tertiary: '#381300',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#592300',
        'on-tertiary-container': '#d8885c',
        'tertiary-fixed': '#ffdbca',
        'tertiary-fixed-dim': '#ffb690',
        'on-tertiary-fixed': '#341100',
        'on-tertiary-fixed-variant': '#723610',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-surface-variant': '#43474f',
        'surface-variant': '#e0e3e5',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#a7c8ff',
        'surface-tint': '#3a5f94',
        outline: '#737780',
        'outline-variant': '#c3c6d1',
        background: '#f7f9fb',
        'on-background': '#191c1e',
        'status-pending': '#fef08a',
        'on-status-pending': '#854d0e',
        'status-active': '#bfdbfe',
        'on-status-active': '#1e3a8a',
        'status-success': '#bbf7d0',
        'on-status-success': '#166534',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '8px',
        'stack-xs': '4px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'stack-xl': '40px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        gutter: '24px',
        'container-max-width': '1440px',
      },
      fontFamily: {
        display: ['Inter'],
        'headline-lg': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'headline-md': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'label-md': ['Inter'],
        'code-sm': ['monospace'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'code-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
